services:
  - type: web
    name: baroharin
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/categories
    envVars:
      - key: APP_JWT_SECRET
        generateValue: true
      - key: H2_CONSOLE_ENABLED
        value: "false"
      - key: APP_CORS_ALLOWED_ORIGINS
        value: ""
